### ISSUE TITLE
Selecting Burst Lasers causes crash

### ISSUE THREAD

**Issue by Psieonic** [cmmcleod/coriolis#45]
Seems like all the Burst Lasers are messed up. Selecting any of them either results in a missing name, or a crash when you try to select something else after selecting a burst laser.

`Browser:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Path:
/outfit/cobra_mk_iii/04A4A4A3A3A3A4C7h1129290k0433455d53536c
Error:
unknown
Message:
Cannot read property 'offsetTop' of undefined
Details:
TypeError: Cannot read property 'offsetTop' of undefined
    at link (http://cdn.coriolis.io/app.39d33c36.js:23:1461)
    at http://cdn.coriolis.io/lib.ba1942cd.js:8:1743
    at $ (http://cdn.coriolis.io/lib.ba1942cd.js:8:1799)
    at M (http://cdn.coriolis.io/lib.ba1942cd.js:6:28284)
    at g (http://cdn.coriolis.io/lib.ba1942cd.js:6:24711)
    at M (http://cdn.coriolis.io/lib.ba1942cd.js:6:28229)
    at g (http://cdn.coriolis.io/lib.ba1942cd.js:6:24711)
    at http://cdn.coriolis.io/lib.ba1942cd.js:6:24235
    at http://cdn.coriolis.io/lib.ba1942cd.js:6:25206
    at m (http://cdn.coriolis.io/lib.ba1942cd.js:6:27418)`

**Comment by Psieonic** [comment]
Doesn't seem to happen with selecting Bursts on a Class 1 slot, only a Class 2 slot.

**Comment by Toxicat** [comment]
Thanks for the bug report. We will investigate it.

**Comment by cmmcleod** [comment]
Same here. I know what the issue is, will fix.

**Comment by cmmcleod** [comment]
Have fix ready will push in 0.10.1

**Comment by cmmcleod** [comment]
Fixed in 0.10.1
