### ISSUE TITLE
"Crash" when clicking on leftmost column on power plant in left component table

### ISSUE THREAD

**Issue by SimonSchick** [cmmcleod/coriolis#64]
### Save involved in crash
http://coriolis.io/outfit/anaconda/28A7A6A5E8A8A5C0o0o0o0o0t0t0q0q00030j03040404035s2d2d2d2d2d2d5d5d5d6b.Iw18ZlA=.EwBj4ywRk29sIA==?bn=MEGA%20FUCKER

### How to reproduce
Click on the power plant at the leftmost column (enable/disable button) in the "Component" table.

### What happens
I was told to report this here (error page is shown).

### What should happen
 Nothing, power plant cannot be disabled.

### General info
```
Browser:
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.61 Safari/537.36
Path:
/outfit/anaconda/28A7A6A5E8A8A5C0o0o0o0o0t0t0q0q00030j03040404035s2d2d2d2d2d2d5d5d5d6b.Iw18ZlA=.EwBj4ywRk29sIA==
Error:
unknown
Message:
Cannot read property 'enabled' of undefined
```

### Console output:

```
TypeError: Cannot read property 'enabled' of undefined
    at m.$scope.togglePwr (http://cdn.coriolis.io/app.7deea037.js:18:4319)
    at fn (eval at <anonymous> (http://cdn.coriolis.io/lib.ba1942cd.js:11:8178), <anonymous>:4:302)
    at f (http://cdn.coriolis.io/lib.ba1942cd.js:11:28577)
    at m.$eval (http://cdn.coriolis.io/lib.ba1942cd.js:9:1146)
    at m.$apply (http://cdn.coriolis.io/lib.ba1942cd.js:9:1372)
    at HTMLTableCellElement.<anonymous> (http://cdn.coriolis.io/lib.ba1942cd.js:11:28629)
    at HTMLTableCellElement.Gf.c (http://cdn.coriolis.io/lib.ba1942cd.js:6:14776) undefined
```

**Comment by cmmcleod** [comment]
Whoops! Great catch. will fix asap

**Comment by cmmcleod** [comment]
Fixed by b707015d9c05c38fa8a4333a65f7786cec844f56

**Comment by cmmcleod** [comment]
0.14.0 deploy. Closing!

**Comment by SimonSchick** [comment]
Neat, thanks!
