### ISSUE TITLE
can't add module

### ISSUE THREAD

**Issue by syl779** [cmmcleod/coriolis#78]
Trying to add a class 3 turreted burst laser in 2nd slot to this build

http://coriolis.io/outfit/anaconda/08C7C6A5D8A8D5C16-0v0v7j7j1313040400030404--060505050404044532F924.Iw18ZlA=.Aw0iMrtln8BYBMBmIA==?bn=Anaconda

Browser:
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; Media Center PC 6.0; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; GWX:RESERVED; rv:11.0) like Gecko

Path:
/outfit/anaconda/08C7C6A5D8A8D5C160o0v0v7j7j1313040400030404--0605050504044a5d32F924.Iw18ZwAzkA==.Aw0iMrtlnIGYHAQFgEyqA===

Error:
unknown

Message:Unable to get property 'getAttribute' of undefined or null reference

Details:
TypeError: Unable to get property 'getAttribute' of undefined or null reference
   at $scope.select (http://cdn.coriolis.io/app.7463842a.js:20:4356)
   at fn (Function code:2:384)
   at f (http://cdn.coriolis.io/lib.5d6ea10b.js:11:29778)
   at n.prototype.$eval (http://cdn.coriolis.io/lib.5d6ea10b.js:10:714)
   at n.prototype.$apply (http://cdn.coriolis.io/lib.5d6ea10b.js:10:943)
   at Anonymous function (http://cdn.coriolis.io/lib.5d6ea10b.js:11:29828)
   at c (http://cdn.coriolis.io/lib.5d6ea10b.js:6:14970)

**Comment by syl779** [comment]
And now it works again after failing 20 times in a row

**Comment by cmmcleod** [comment]
Will Test in IE and try to replicate. This could be a legitimate bug.

**Comment by cmmcleod** [comment]
Will be fixed in latest release - 1.5.0
