### ISSUE TITLE
Crashes wile adding a weapon

### ISSUE THREAD

**Issue by Vacendack** [cmmcleod/coriolis#79]
I tried to add a Burst laser 3G to the second weapon slot of a Pyton, and everytime ir crashes thebuild, and it is not stored

this is the dump

Browser:
Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; ARMBJS; rv:11.0) like Gecko

Path:
/outfit/python/07E6E5E4E7E6E5C1e--1717----04044j03---002h.Iw18eQ==.Aw18eQ==

Error:
unknown

Message:Object doesn't support property or method 'getAttribute'

Details:
TypeError: Object doesn't support property or method 'getAttribute'
   at $scope.select (http://cdn.coriolis.io/app.7463842a.js:20:4274)
   at fn (Function code:2:384)
   at f (http://cdn.coriolis.io/lib.5d6ea10b.js:11:29778)
   at n.prototype.$eval (http://cdn.coriolis.io/lib.5d6ea10b.js:10:714)
   at n.prototype.$apply (http://cdn.coriolis.io/lib.5d6ea10b.js:10:943)
   at Anonymous function (http://cdn.coriolis.io/lib.5d6ea10b.js:11:29828)
   at c (http://cdn.coriolis.io/lib.5d6ea10b.js:6:14970)

**Comment by cmmcleod** [comment]
The appears to be the same issue at #78. Closing in favor of #78
