### ISSUE TITLE
Frequent problems when I try to refresh a Comparison

### ISSUE THREAD

**Issue by electricm** [cmmcleod/coriolis#96]
Frequently, when I'm refreshing a saved ship comparison or loading one up that I've created before, I get an error and I'm unable to access that comparison.

Browser:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Path:
/compare/Progression
Error:
unknown
Message:
Cannot read property 'split' of undefined
Details:
TypeError: Cannot read property 'split' of undefined
    at toShip (http://cdn.coriolis.io/app.0a3b6bbc.js:12:1422)
    at n.$scope.addBuild (http://cdn.coriolis.io/app.0a3b6bbc.js:13:1163)
    at http://cdn.coriolis.io/app.0a3b6bbc.js:13:3742
    at Array.forEach (native)
    at new <anonymous> (http://cdn.coriolis.io/app.0a3b6bbc.js:13:3715)
    at e (http://cdn.coriolis.io/lib.51f691b1.js:6:16982)
    at Object.instantiate (http://cdn.coriolis.io/lib.51f691b1.js:6:17099)
    at http://cdn.coriolis.io/lib.51f691b1.js:8:5937
    at http://cdn.coriolis.io/lib.51f691b1.js:14:23333
    at $ (http://cdn.coriolis.io/lib.51f691b1.js:8:2162)

**Comment by cmmcleod** [comment]
Can you provide the back JSON to help me investigate?

Go To `Settings` -> `Backup` then copy the output JSON and paste it here

**Comment by cmmcleod** [comment]
Any chance you can provide your JSON backup data?
